### ISSUE TITLE
Voltage-Regulated Driving

### ISSUE THREAD

**Issue by ayushdewan** [Team2489/Generic-Robot-Code#6]
Usually FRC battery voltage can cross 12 volts (which is a good thing) and indicates the battery will last pretty long, or it can dip below 12V (not good). 

If pushed the joystick halfway (leftSpeed and rightSpeed are both 0.5 so we expect 0.5 * 12V = 6V):
if battery voltage = 13V, applied voltage = 6.5V
if battery voltage = 11V, applied voltage = 5.5V

We expected 6V but got different values. This leads to inconsistent driving and control loops.
Multiply leftSpeed and rightSpeed by 12 / batteryVoltage where batteryVoltage = leftFrontMaster.getBusVoltage()

**Comment by ayushdewan** [comment]
``` java
double kLVoltage = 12 / leftFrontMotor.getBusVoltage();
double kRVoltage = 12 / rightFrontMotor.getBusVoltage();
leftFrontMotor.set(ControlMode.PercentOutput, -leftSpeed * kLVoltage);
rightFrontMotor.set(ControlMode.PercentOutput, rightSpeed * kRVoltage);
```

**Comment by aditya917** [comment]
I am having a problem with this code because it gives me an error.
`  
  double kLVoltage = 12 / leftFrontMaster.getBusVoltage();
  double kRVoltage = 12/rightFrontMaster.getBusVoltage();
    
Robot.drivetrain.rightFrontMaster.set(ControlMode.PercentOutput,-Robot.oi.rightJoystick.getY()*kRVoltage);
  Robot.drivetrain.leftFrontMaster.set(ControlMode.PercentOutput,Robot.oi.leftJoystick.getY()*kLVoltage);`

The rightFrontMaster and leftFrontMaster cannot be resolved to a type.

**Comment by ayushdewan** [comment]
change it to:
``` java
double kLVoltage = 12 / Robot.drivetrain.leftFrontMaster.getBusVoltage();
double kRVoltage = 12 / Robot.drivetrain.rightFrontMaster.getBusVoltage();

Robot.drivetrain.rightFrontMaster.set(ControlMode.PercentOutput,-Robot.oi.rightJoystick.getY()*kRVoltage);
Robot.drivetrain.leftFrontMaster.set(ControlMode.PercentOutput,Robot.oi.leftJoystick.getY()*kLVoltage);
```

**Comment by aditya917** [comment]
Thanks for the help. I fixed the changes.
